### <p style="text-align: right;"> Alexis Guevara

# LU Factorization on Banded Matrices

In [39]:
import numpy as np

In [5]:
def bandLU(K, p, q):
    # INPUTS - K: 2D numpy array representing the banded matrix to be factored
    #          p: an integer representing the lower bandwidth 
    #          q: an integer representing the upper bandwidth
    # OUTPUT - K: 2D numpy array

    n = len(K)
    for m in range(n-1):
        for i in range(m+1 , min(m+p+1,n)):
            K[i, m] = K[i,m] / K[m,m]
        for j in range(m+1 , min(m+q+1,n)):
            for i in range(m+1 , min(m+p+1,n)):
                K[i,j] = K[i,j] - K[i,m] * K[m,j]
    return K

In [6]:
#Test Case
# Example 1:
K = np.array([[1, 2, 4], 
              [3, 8, 14], 
              [2, 6, 13]], 
             dtype=float)
p = 1 # lower bandwidth
q = 1 # upper bandwidth

LU = bandLU(K,p,q)
print(LU)

[[  1.   2.   4.]
 [  3.   2.  14.]
 [  2.   3. -29.]]


In [8]:
def bandforward(L,f,p):
    # INPUTS - L: 2D numpy array representing the banded lower triangular matrix
    #          f: 1D numpy array representing the RHS of the matrix equation Lz = f 
    #          p: an integer representing the lower bandwidth
    # OUTPUT - z: 1D numpy array representing the solution of Lz = f
    n = L.shape[0]
    z = np.zeros(n)
    for i in range(n):
        sum_val = 0
        for j in range(max(0, i-p), i):
            sum_val += L[i, j] * z[j]
        z[i] = (f[i] - sum_val) / L[i, i]
    return z

In [10]:
def bandbackward(U,f,q):
    # INPUTS - U: 2D numpy array representing the banded upper triangular matrix
    #          f: 1D numpy array representing the RHS of the matrix equation Lz = f
    #          q: an integer representing the upper bandwidth
    # OUTPUT - 

    n = U.shape[0]
    w = np.zeros(n)
    for i in range(n-1, -1, -1):
        sum_val = 0
        for j in range(i+1, min(i+q+1,n)):
            sum_val += U[i, j] * w[j]
        w[i] = (f[i] - sum_val) / U[i, i]
    return w

## Test Cases

In [12]:
def create_random_band_matrix(n,p,q):
    # Create a random banded matrix with: 
    # - dimensions n x n 
    # - lower bandwidth p 
    # - upper bandwidth q
    K = np.zeros((n, n))
    for i in range(n):
        for j in range(max(0, i-p), min(n,i+q+1)):
            K[i,j] = np.random.random()
    return K

# Example usage:
n = 5  # Size of the matrix
p = 3  # Lower bandwidth
q = 1  # Upper bandwidth
K = create_random_band_matrix(n, p, q)
print("Random banded matrix K:\n", K)

Random banded matrix K:
 [[0.32061164 0.8094554  0.         0.         0.        ]
 [0.0790247  0.38348249 0.65850857 0.         0.        ]
 [0.49062864 0.95160923 0.56847226 0.86089419 0.        ]
 [0.03241042 0.43473524 0.24732936 0.75899642 0.41081353]
 [0.         0.61652138 0.38233584 0.77973232 0.45792674]]


In [13]:
#Test Case
# Example 1:
K = np.array([[1, 2, 4], 
              [3, 8, 14], 
              [2, 6, 13]], 
             dtype=float)
p = 1 # lower bandwidth
q = 1 # upper bandwidth

LU = bandLU(K,p,q)
print(LU)

[[  1.   2.   4.]
 [  3.   2.  14.]
 [  2.   3. -29.]]


In [14]:
# Example 2:
L = np.array([[1, 0, 0, 0], [3, 1, 0, 0], [0, 2, 1, 0], [0, 0, 1, 1]], dtype=float)
f = np.array([1, 5, 6, 4], dtype=float)
p = 1  # lower bandwidth

z = bandforward(L, f, p)
print(z.reshape(-1,1))

[[1.]
 [2.]
 [2.]
 [2.]]


In [15]:
# Example 3:
U = np.array([[2, 3, 0, 0], [0, 7, 4, 0], [0, 0, 5, 3], [0, 0, 0, 2]], dtype=float)
f = np.array([1, 5, 6, 4], dtype=float)
q = 2  # upper bandwidth

w = bandbackward(U, f, q)
print(w.reshape(-1,1))

[[-0.57142857]
 [ 0.71428571]
 [ 0.        ]
 [ 2.        ]]


In [16]:
import numpy as np

# Function to perform LU factorization on a banded matrix
def bandLU(K, p, q):
    n = K.shape[0]
    # Loop over each column up to the second last one
    for m in range(n - 1):
        # Update the lower triangular part of K
        for i in range(m + 1, min(m + p + 1, n)):
            K[i, m] /= K[m, m]
        # Update the upper triangular part of K
        for j in range(m + 1, min(m + q + 1, n)):
            for i in range(m + 1, min(m + p + 1, n)):
                K[i, j] -= K[i, m] * K[m, j]
    return K

#Test Case
# Example 1:
K = np.array([[1, 2, 4], 
              [3, 8, 14], 
              [2, 6, 13]], 
             dtype=float)
p = 1 # lower bandwidth
q = 1 # upper bandwidth

# Perform LU factorization
LU = bandLU(K, p, q)
print("Modified matrix K after bandLU:\n", LU)


Modified matrix K after bandLU:
 [[  1.   2.   4.]
 [  3.   2.  14.]
 [  2.   3. -29.]]


In [17]:
import numpy as np

def bandLU(K, p, q):
    n = K.shape[0]
    
    for m in range(n - 1):
        for i in range(m + 1, min(m + p + 1, n)):
            K[i, m] = K[i, m] / K[m, m]
        for j in range(m + 1, min(m + q + 1, n)):
            for i in range(m + 1, min(m + p + 1, n)):
                K[i, j] = K[i, j] - K[i, m] * K[m, j]
    return K

# Example usage
K = np.array([[4, -1, 0, 0], 
              [-1, 4, -1, 0], 
              [0, -1, 4, -1], 
              [0, 0, -1, 4]], dtype=float)
p, q = 1, 1
print(bandLU(K, p, q))


[[ 4.         -1.          0.          0.        ]
 [-0.25        3.75       -1.          0.        ]
 [ 0.         -0.26666667  3.73333333 -1.        ]
 [ 0.          0.         -0.26785714  3.73214286]]


In [18]:
def bandforward(L, f, p):
    """
    INPUTS - L: 2D numpy array representing the banded lower triangular matrix
             f: 1D numpy array representing the RHS of the matrix equation Lz = f
             p: an integer representing the lower bandwidth
    OUTPUT - z: 1D numpy array representing the solution of Lz = f
    """
    n = len(L)  # Size of Matrix L
    z = np.zeros(n) # Initialize solution vector of Lz = f

    for i in range(n):
        z[i] = f[i]
        for j in range(max(0, i - p), i):
            z[i] = z[i] - L[i, j] * z[j]
        z[i] = z[i] / L[i, i]  # Divide by diagonal element
    return z

In [19]:
# Example 2
# Predefined lower triangular matrix
L = np.array([[1, 0, 0],
              [3, 1, 0],
              [2, 1, 1]], dtype=np.float64)

f1 = np.array([1,1,1])
p = 0  # Upper bandwidth

# Perform LU factorization
z = bandforward(L, f1, p)
print("Solution of Lz = f:\n", z.reshape(-1,1))

Solution of Lz = f:
 [[1.]
 [1.]
 [1.]]


In [20]:
def bandbackward(U, f, q):
    """
    INPUTS - U: 2D numpy array representing the banded upper triangular matrix
             f: 1D numpy array representing the RHS of the matrix equation Lz = f
             q: an integer representing the upper bandwidth
    OUTPUT - w: 1D numpy array representing the solution of Uw = f
    """
    n = U.shape[0]
    w = np.zeros(n)
    ## Loop over each row in reverse order
    for i in range(n-1, -1, -1):
        w[i] = f[i]  # Start with right-hand side value
        # Subtract known values from following rows
        for j in range(i + 1, min(i + q + 1, n)):
            w[i] = w[i] - U[i, j] * w[j]
        w[i] = w[i] / U[i, i]  # Divide by diagonal element
    return w

In [21]:
# Example 3
# Predefined lower triangular matrix
U = np.array([[1, 2, 4],
              [0, 2, 2],
              [0, 0, 3]], dtype=np.float64)

f2 = np.array([1,2,4], dtype=np.float64) 
q = 2  # Upper bandwidth

# Perform LU factorization
w = bandbackward(U, f2, q)
print("Solution of Uw = f:\n", w.reshape(-1,1))

Solution of Uw = f:
 [[-3.66666667]
 [-0.33333333]
 [ 1.33333333]]
